development:
  adapter: postgresql
  database: blck_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: blck_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: blck_box
  user: <INSERT USER HERE>
  password: <INSERT PASSWORD HERE>
  pool: 5
  timeout: 5000
